<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxHeACg\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxHeACg/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerCxHeACg.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerCxHeACg\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerCxHeACg\appAppKernelProdContainer([
    'container.build_hash' => 'CxHeACg',
    'container.build_id' => '7721523d',
    'container.build_time' => 1709798081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxHeACg');
